name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test_auth_api
        working-directory: ./backend
        run: python -m pytest tests/test_auth_api.py -v --tb=long

      - name: test_clients_api
        working-directory: ./backend
        run: python -m pytest tests/test_clients_api.py -v --tb=long

      - name: test_client_service
        working-directory: ./backend
        run: python -m pytest tests/test_client_service.py -v --tb=long

      - name: test_client_repository
        working-directory: ./backend
        run: python -m pytest tests/test_client_repository.py -v --tb=long

      - name: test_interaction_api
        working-directory: ./backend
        run: python -m pytest tests/test_interaction_api.py -v --tb=long

      - name: test_interaction_service
        working-directory: ./backend
        run: python -m pytest tests/test_interaction_service.py -v --tb=long

      - name: test_interaction_repository
        working-directory: ./backend
        run: python -m pytest tests/test_interaction_repository.py -v --tb=long

      - name: test_integration_post
        working-directory: ./backend
        run: python -m pytest tests/test_integration_post.py -v --tb=long

      - name: test_metrics_api
        working-directory: ./backend
        run: python -m pytest tests/test_metrics_api.py -v --tb=long
